return function(opts, colors)
  return {
    LspReferenceText = { bg = colors.shade_gray, style = opts.styles.references },
    LspReferenceRead = { bg = colors.shade_gray, style = opts.styles.references },
    LspReferenceWrite = { bg = colors.shade_gray, style = opts.styles.references },
    LspReferenceTarget = { bg = colors.highlight },
    LspInlayHint = { fg = colors.gray, bg = colors.shade_gray, style = 'italic,bold' },
    LspCodeLens = { fg = colors.high_gray },
    --TODO:testing
    LspCodeLensSeparator = { fg = colors.purple, bg = colors.shade_purple },
    LspSignatureActiveParameter = { fg = colors.match, bg = colors.shade_cyan, style = 'bold' },

    DiagnosticError = { fg = colors.error, style = opts.styles.virtualtext },
    DiagnosticWarn = { fg = colors.warn, style = opts.styles.virtualtext },
    DiagnosticInfo = { fg = colors.info, style = opts.styles.virtualtext },
    DiagnosticHint = { fg = colors.hint, style = opts.styles.virtualtext },
    DiagnosticOk = { fg = colors.ok, style = opts.styles.virtualtext },
    DiagnosticVirtualTextError = {
      fg = colors.low_red,
      bg = colors.shade_gray,
      sp = colors.low_red,
      style = opts.styles.virtualtext,
    },
    DiagnosticVirtualTextWarn = { fg = colors.low_olive, bg = colors.shade_gray, style = opts.styles.virtualtext },
    DiagnosticVirtualTextInfo = { fg = colors.low_blue, bg = colors.shade_gray, style = opts.styles.virtualtext },
    DiagnosticVirtualTextHint = {
      fg = colors.low_purple,
      bg = colors.shade_purple,
      style = opts.styles.virtualtext,
    },
    DiagnosticVirtualTextOk = { fg = colors.low_green, bg = colors.shade_gray, style = opts.styles.virtualtext },
    -- DiagnosticVirtualLinesError = {},
    -- DiagnosticVirtualLinesWarn =  {},
    -- DiagnosticVirtualLinesInfo =  {},
    -- DiagnosticVirtualLinesHint =  {},
    -- DiagnosticVirtualLinesOk =    {},
    DiagnosticUnderlineError = { style = opts.styles.diagnostics, sp = colors.error },
    DiagnosticUnderlineWarn = { style = opts.styles.diagnostics, sp = colors.warn },
    DiagnosticUnderlineInfo = { style = opts.styles.diagnostics, sp = colors.info },
    DiagnosticUnderlineHint = { style = opts.styles.diagnostics, sp = colors.hint },
    DiagnosticUnderlineOk = { style = opts.styles.diagnostics, sp = colors.ok },
    DiagnosticFloatingError = { fg = colors.error },
    DiagnosticFloatingWarn = { fg = colors.warn },
    DiagnosticFloatingInfo = { fg = colors.info },
    DiagnosticFloatingHint = { fg = colors.hint },
    DiagnosticFloatingOk = { fg = colors.ok },
    DiagnosticSignError = { fg = colors.error },
    DiagnosticSignWarn = { fg = colors.warn },
    DiagnosticSignInfo = { fg = colors.info },
    DiagnosticSignHint = { fg = colors.hint },
    DiagnosticSignOk = { fg = colors.ok },
    DiagnosticDeprecated = { fg = colors.high_red, sp = colors.high_red, style = opts.styles.deprecated },
    DiagnosticUnnecessary = { bg = colors.shade_purple },
  }
end
