return function(opts, colors)
  return {
    Comment = { fg = colors.low_gray, style = opts.styles.comments },
    Constant = { fg = colors.high_gray },
    String = { fg = colors.green, opts.styles.strings },
    Character = { fg = colors.green },
    Number = { fg = colors.orange },
    Float = { fg = colors.orange },
    Identifier = { fg = colors.fg, style = opts.styles.variables },
    Function = { fg = colors.cyan, style = opts.styles.functions },
    Statement = { fg = colors.gray },
    Conditional = { fg = colors.purple, style = opts.styles.keywords },
    Repeat = { fg = colors.purple, style = opts.styles.keywords },
    Boolean = { fg = colors.orange },
    Label = { fg = colors.high_purple },
    Operator = { fg = colors.red },
    Keyword = { fg = colors.gray, style = opts.styles.keywords },
    Exception = { fg = colors.purple },
    PreProc = { fg = colors.purple },
    Include = { fg = colors.high_cyan },
    Define = { fg = colors.high_cyan },
    Macro = { fg = colors.high_cyan },
    PreCondit = { fg = colors.purple },
    Type = { fg = colors.low_olive },
    StorageClass = { fg = colors.high_purple },
    Structure = { fg = colors.olive },
    Typedef = { fg = colors.low_purple },
    Special = { fg = colors.olive },
    SpecialChar = { fg = colors.olive },
    Tag = { fg = colors.green },
    Delimiter = { fg = colors.low_olive },
    -- special things inside a comment
    SpecialComment = { fg = colors.gray, style = opts.styles.comments },
    Debug = { fg = colors.red },
    Underlined = { fg = colors.green, sp = colors.green, style = 'underline' },
    Ignore = { fg = colors.high_red, bg = colors.bg, style = 'bold' },
    Error = { fg = colors.error, bg = colors.none, style = 'bold' },
    Todo = { fg = colors.low_olive, style = 'bold' },
    Added = { fg = colors.high_cyan, opts.styles.diff },
    Changed = { fg = colors.high_green, opts.styles.diff },
    Removed = { fg = colors.high_red, opts.styles.diff },

    -- diff
    diffAdded = { fg = colors.green },
    diffChanged = { fg = colors.green },
    diffRemoved = { fg = colors.red },
    diffFile = { fg = colors.blue },
    diffNewFile = { link = 'Added' },
    diffOldFile = { link = 'Removed' },
    diffSubname = { fg = colors.low_purple },
    diffLine = { fg = colors.purple },
    diffIndexLine = { fg = colors.orange },
    diffComment = { link = 'comment' },
  }
end
