return function(opts, colors)
  return {
    ['@Macro'] = { link = 'Macro' },
    ['@attribute'] = { fg = colors.red },
    ['@boolean'] = { link = 'Boolean' },
    ['@character'] = { link = 'Character' },
    ['@character.special'] = { link = 'SpecialChar' },
    ['@comment'] = { link = 'Comment' },
    ['@comment.error'] = { link = '@error' },
    ['@comment.note'] = { fg = colors.blue },
    ['@comment.todo'] = { link = 'Todo' },
    ['@comment.warning'] = { link = '@warning' },
    ['@conditional'] = { link = 'Conditional' },
    ['@constant'] = { link = 'Constant' },
    ['@constant.builtin'] = { fg = colors.cyan },
    ['@constant.macro'] = { fg = colors.low_cyan },
    ['@constructor'] = { fg = colors.olive },
    ['@danger'] = { fg = colors.error, style = 'bold' },
    ['@define'] = { link = 'Define' },
    ['@error'] = { link = 'Error' },
    ['@exception'] = { link = 'Exception' },
    ['@field'] = { fg = colors.gray },
    ['@float'] = { link = 'Float' },
    ['@function'] = { link = 'Function' },
    ['@function.builtin'] = { fg = colors.high_cyan, style = opts.styles.functions },
    ['@function.call'] = { link = 'Function' },
    ['@function.macro'] = { link = 'Function' },
    ['@function.method'] = { link = 'Function' },
    ['@include'] = { fg = colors.high_cyan },
    ['@keyword'] = { link = 'Keyword' },
    ['@keyword.conditional'] = { link = 'Conditional' },
    ['@keyword.conditional.ternary'] = { link = '@keyword.operator' },
    ['@keyword.coroutine'] = { fg = colors.bule, style = 'bold' },
    ['@keyword.function'] = { fg = colors.cyan, style = opts.styles.keywords },
    ['@keyword.import'] = { fg = colors.cyan, style = opts.styles.keywords },
    ['@keyword.modifier'] = { fg = colors.low_purple },
    ['@keyword.operator'] = { fg = colors.red, style = opts.styles.keywords },
    ['@keyword.repeat'] = { link = 'Repeat' },
    ['@keyword.return'] = { fg = colors.cyan, style = opts.styles.keywords },
    ['@keyword.type'] = { fg = colors.olive },
    ['@label'] = { link = 'Label' },
    ['@markup'] = { fg = colors.fg },
    ['@markup.environment'] = { link = '@text.environment' },
    ['@markup.environment.name'] = { link = '@text.environment.name' },
    ['@markup.heading']  = { fg = colors.bg, bg = colors.fg, style = 'bold' },
    ['@markup.heading.1'] = { fg = colors.bg, bg = colors.high_orange, style = 'bold' },
    ['@markup.heading.2'] = { fg = colors.bg, bg = colors.high_purple, style = 'bold' },
    ['@markup.heading.3'] = { fg = colors.bg, bg = colors.high_olive, style = 'bold' },
    ['@markup.heading.4'] = { fg = colors.bg, bg = colors.high_green, style = 'bold' },
    ['@markup.heading.5'] = { fg = colors.bg, bg = colors.high_cyan, style = 'bold' },
    ['@markup.heading.6'] = { fg = colors.bg, bg = colors.high_blue, style = 'bold' },
    ['@markup.link'] = { fg = colors.purple },
    ['@markup.link.url'] = { link = '@string.special.url' },
    ['@markup.list.checked'] = { fg = colors.green },
    ['@markup.list.unchecked'] = { link = '@note' },
    ['@markup.math'] = { fg = colors.fg },
    ['@markup.raw'] = { fg = colors.fg, bg = colors.nc },
    ['@markup.raw.block'] = { bg = colors.nc },
    ['@markup.underline'] = { style = 'underline' },
    ['@method'] = { fg = colors.cyan },
    ['@module'] = { fg = colors.olive },
    ['@module.builtin'] = { link = '@module' },
    ['@namespace'] = { fg = colors.olive },
    ['@note'] = { fg = colors.info, style = 'bold' },
    ['@number'] = { link = 'Number' },
    ['@operator'] = { link = 'Operator' },
    ['@parameter'] = { fg = colors.high_blue },
    ['@parameter.reference'] = { fg = colors.red },
    ['@property'] = { fg = colors.blue },
    ['@punctuation.bracket'] = { fg = colors.low_olive },
    ['@punctuation.delimiter'] = { fg = colors.low_olive },
    ['@punctuation.special'] = { fg = colors.olive },
    ['@repeat'] = { link = 'Repeat' },
    ['@string'] = { fg = colors.green, style = opts.styles.strings },
    ['@string.escape'] = { fg = colors.high_green, style = 'bold' },
    ['@string.regexp'] = { fg = colors.high_green },
    ['@string.special'] = { link = 'Special' },
    ['@string.special.path'] = { fg = colors.green },
    ['@string.special.url'] = { fg = colors.high_blue, sp = colors.high_blue, style = 'underline' },
    ['@symbol'] = { fg = colors.cyan },
    ['@tag'] = { fg = colors.olive },
    ['@tag.attribute'] = { fg = colors.red },
    ['@tag.delimiter'] = { fg = colors.low_olive },
    ['@text'] = { fg = colors.fg },
    ['@text.emphasis'] = { fg = colors.olive, style = 'italic' },
    ['@text.environment'] = { fg = colors.high_red },
    ['@text.environment.name'] = { fg = colors.high_red },
    ['@text.literal'] = { fg = colors.green },
    ['@text.math'] = { fg = colors.high_cyan },
    ['@text.reference'] = { fg = colors.high_cyan },
    ['@text.strong'] = { fg = colors.fg, style = 'bold' },
    ['@text.title'] = { fg = colors.high_blue, style = 'bold' },
    ['@text.underline'] = { style = 'underline' },
    ['@text.uri'] = { fg = colors.high_blue, sp = colors.high_blue, style = 'underline' },
    ['@type'] = { link = 'Type' },
    ['@type.builtin'] = { fg = colors.low_olive },
    ['@variable'] = { fg = colors.fg, style = opts.styles.variables },
    ['@variable.builtin'] = { fg = colors.high_cyan, style = opts.styles.variables },
    ['@variable.member'] = { fg = colors.blue, style = opts.styles.variables },
    ['@variable.parameter'] = { link = '@parameter' },
    ['@variable.parameter.builtin'] = { link = '@variable.builtin' },
    ['@warning'] = { fg = colors.warn, style = 'bold' },
  }
end
